### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by johnkrovitch** [larriereguichet/AdminBundle#33]

**Comment by lutangar** [comment]
@johnkrovitch I'd like to recommend the AdminBundle to a mate, but I'm not sure the documentation is up to date; at least to create a basic CRUD.
Is it doable at the moment?

**Comment by johnkrovitch** [comment]
@lutangar Unfortunately it is not ready yet for production. There is some few bugs and the documentation is not updated too. It will be done in a few months.
